#!/usr/bin/bash
################################################################
# CanAirIO Deploy Util
# ====================
# 
# (C) @hpsaturn 2022
#
# Original tool for deploy flavors of CanAirIO firmware.
#
# REVISIONS
# +++++++++
# 20220713 General changes for try to hava a better generic tool 
################################################################

SRC_REV=`cat platformio.ini | grep 'revision =' | awk '{print $3}'`
SRC_VER=`cat platformio.ini | grep 'version =' | awk '{print $3}'`
TARGET=`cat platformio.ini | grep 'target =' | awk '{print $3}'`
DATE=`date +%Y%m%d`
OUTDIR=".pio/build"
RELDIR="releases"
BINDIR="binaries"
MANIFEST="manifest"
NAME="canairio"
DEFAULT="TTGO_T7"
OWNER="kike-canaries"
REPO="canairio_firmware"
INSDIR=$RELDIR/installer/${NAME}_installer
PIO_HOME=${HOME}/.platformio

flavors="TTGO_T7 TTGO_TDISPLAY ESP32DEVKIT M5PICOD4 HELTEC WEMOSOLED TTGO_TQ M5ATOM M5STICKCPLUS ESP32C3LOLIN ESP32C3SEEDX ESP32C3OIPLUS AG_OPENAIR ESP32S2LOLIN TTGO_T7S3 ESP32S3 XIAO_S3 XIAO_C6"
flavors_ci="TTGO_TDISPLAY ESP32C3LOLIN ESP32S2LOLIN TTGO_T7S3 XIAO_C6"

showHelp () {
  echo
  echo "************************************************"
  echo "** Build release flavor or installer package **"
  echo "************************************************"
  echo
  echo "Usage: ./build [flavor|wokwi|all|list|installer|github|ota|webi|ci|help|print|list|clean]"
  echo
  echo "example: ./build clean"
  echo "example: ./build all"
  echo -n "example: ./build "; echo ${flavors} | awk '{print $1}'
  echo "example: ./build installer"
  echo
  echo "Supported boards: "
  echo "./build list"
  echo
  echo "Small CI test:"
  echo "./build ci"
  echo
  echo "Build installer option will build a installer package for Linux"
  echo "with OTA support and USB support"
  echo
}

clean () {
  echo "Clean installer directory.."
  rm -rf $RELDIR/$BINDIR
  rm -rf $RELDIR/$MANIFEST
  rm -rf $RELDIR/wokwi
  rm -f $INSDIR/*.bin
  rm -f $INSDIR/*.py  
  for flavor in $flavors; do
    echo "Clean flavor $flavor.."
    pio run -s -e $flavor -t clean
    rm -f "sdkconfig.$flavor"
  done
  # we need repeat this because clean generate it
  echo "Clean Manifests.."
  rm -rf $RELDIR/$MANIFEST
}

build () {
  echo
  echo "***********************************************"
  echo "** Building $1"
  echo "***********************************************"
  echo

  pio run -s -e $1
  if [ $? -ne 0 ]; then
    echo "ERROR: pio build failed for flavor $1"
    exit 1
  fi

  echo
  echo "***********************************************"
  echo "** Firmware $1 output:"
  echo "***********************************************"
  FIRMDIR=$RELDIR/$BINDIR/$1
  mkdir -p $FIRMDIR 
  cp $OUTDIR/$1/firmware.bin $FIRMDIR/${NAME}_${1}_rev${SRC_REV}.bin
  if [ $1 == ESP32C3 ] || [ $1 == ESP32C3LOLIN ] || [ $1 == ESP32C3SEEDX ] || [ $1 == ESP32C3OIPLUS ]; then
    python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool.py --chip esp32c3 merge_bin -o  $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 80m --flash_size 4MB 0x0000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
  elif [ $1 == ESP32S3 ] || [ $1 == TTGO_T7S3 ] || [ $1 == XIAO_S3 ]; then
    python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool.py --chip esp32s3 merge_bin -o  $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 80m --flash_size 8MB 0x0000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
  elif [ $1 == ESP32S2LOLIN ]; then
    python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool.py --chip esp32s2 merge_bin -o  $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 80m --flash_size 8MB 0x0000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
  elif [ $1 == XIAO_C6 ]; then
    python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool --chip esp32c6 merge-bin -o  $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash-mode dio --flash-freq 80m --flash-size 8MB 0x0000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
  else
    python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool.py --chip esp32 merge_bin -o $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 40m --flash_size 4MB 0x1000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
  fi
  echo "MD5:"
  md5sum $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin
  md5sum $FIRMDIR/${NAME}_${1}_rev${SRC_REV}.bin
  echo "***********************************************"
}

wokwi_setup () {
  mkdir -p $RELDIR/wokwi
  FIRMDIR=$RELDIR/$BINDIR/ESP32WOKWI
  cp $FIRMDIR/${NAME}_ESP32WOKWI_rev${SRC_REV}_merged.bin $RELDIR/wokwi/firmware.bin 
  cp $OUTDIR/ESP32WOKWI/firmware.elf $RELDIR/wokwi/firmware.elf
  du -hs $RELDIR/wokwi/*
  md5sum $RELDIR/wokwi/firmware.bin
  md5sum $RELDIR/wokwi/firmware.elf
}

buildInstaller () {
  check_firmware_dir
  echo "***********************************************"
  echo "** Building installer with target: $TARGET"
  echo "***********************************************"
  echo
  echo "Update installer tool.."
  cp ${PIO_HOME}/packages/tool-esptoolpy/esptool.py $INSDIR/
  echo "Update installer flavors.."
  rm -f $INSDIR/*.bin
  cp $RELDIR/$BINDIR/*/*${SRC_REV}_merged.bin $INSDIR/
  cp ${PIO_HOME}/packages/tool-esptoolpy/esptool.py $INSDIR/
  printOutput
  cd $INSDIR/..
  rm -f ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
  zip -r ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip ${NAME}_installer
  echo
  du -hs ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
  echo
}

print_publish_summary () {
  echo 
  echo "****************************"
  echo "** ! ! W A R N I N G ! ! **"
  echo "***************************"
  echo 
  echo "Publish release:"
  echo 
  echo "${NAME}_${SRC_VER}_rev${SRC_REV}"
  echo "TARGET: ${TARGET}"
  echo
}

check_firmware_dir () {
  FIRMDIR=$RELDIR/$BINDIR
  if [ ! -d "$FIRMDIR" ]; then
    echo "ERROR: Please first build any flavor!"
    exit 1
  fi
}

check_installer () {
  if [ ! -e ${RELDIR}/installer/${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip ]; then
    echo "ERROR: Please run first: 'build installer'"
    exit 1
  fi
}

check_confirmation () {
  read -p "Are you sure? " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]
  then
    exit 1
  fi
  echo
}

publish_release () {
  check_installer 
  print_publish_summary  
  check_confirmation
  cd $INSDIR/..
  # github-release upload --owner ${OWNER} --repo ${REPO} --tag "rev${SRC_REV}" --release-name "rev${SRC_REV} v${SRC_VER}" --body "${COMMIT_LOG}" ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
  echo "Publishing release: v${SRC_VER} rev${SRC_REV}" 
  echo "uploading: ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip"
  git tag -a "v${SRC_VER}" -m "release v${SRC_VER} rev${SRC_REV}"
  git push origin "v${SRC_VER}"
  git log -n 10 --pretty=format:"%h %s" | gh release create "v${SRC_VER}" -F - -t "v${SRC_VER} rev${SRC_REV}" -p ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
}

publish_release_ota () {
  check_installer 
  print_publish_summary  
  check_confirmation 
  scp $RELDIR/$BINDIR/*/*${SRC_REV}.bin canairio:$canairio_target/$TARGET
  scp $RELDIR/$MANIFEST/$TARGET/*.json canairio:$canairio_target/$TARGET
}

publish_release_webtools () {
  check_installer 
  print_publish_summary  
  check_confirmation 
  scp $INSDIR/*.bin canairio:$canairio_target/webi/$TARGET 
  scp $INSDIR/*.txt canairio:$canairio_target/webi/$TARGET 
  scp $INSDIR/*.md canairio:$canairio_target/webi/$TARGET 
  scp $RELDIR/$MANIFEST/webi/$TARGET/*.json canairio:$canairio_target/webi/$TARGET
}
print_time () {
  echo
  secs=$SECONDS
  printf 'TOTAL TIME: %02dh:%02dm:%02ds\r\n' $((secs/3600)) $((secs%3600/60)) $((secs%60))
  echo
}

mark=0

print_time_mark () {
  secs=$((SECONDS - mark))
  printf 'LAST BUILD: %02dh:%02dm:%02ds\r\n' $((secs/3600)) $((secs%3600/60)) $((secs%60))
  mark=$SECONDS
}

printOutput () {
  echo
  check_firmware_dir 
  mkdir -p $INSDIR
  rm -f $INSDIR/md5output.txt
  touch $INSDIR/md5output.txt
  cd $FIRMDIR
  for flavor in *; do
    MD5FLAVOR=`md5sum $flavor/${NAME}_${flavor}_rev${SRC_REV}_merged.bin`
    echo $MD5FLAVOR >> ../../$INSDIR/md5output.txt
  done
  cat ../../$INSDIR/md5output.txt
  cd ../..
  print_time
}


if [ "$1" = "" ]; then
  showHelp
else
  case "$1" in
    clean)
      clean
      ;;

    installer)
      buildInstaller
      ;;

    help)
      showHelp
      ;;

    --help)
      showHelp
      ;;

    -help)
      showHelp
      ;;

    print)
      SECONDS=0 
      printOutput
      ;;

    all)
      SECONDS=0 
      for flavor in $flavors; do
          build $flavor
          print_time_mark
      done     
      printOutput
      ;;

    ci)
      SECONDS=0 
      for flavor in $flavors_ci; do
          build $flavor
          print_time_mark
      done     
      printOutput
      ;;
    
    wokwi)
      build ESP32WOKWI
      wokwi_setup
      ;;

    github)
      publish_release
      ;;

    ota)
      publish_release_ota
      ;;

    webi)
      publish_release_webtools
      ;;

    list)
      for flavor in $flavors; do
          echo $flavor
      done
      ;;

    *)
      if [[ $flavors == *"$1"* ]]; then
        SECONDS=0 
        build $1
        print_time
      else
        echo
        echo "ERROR: Flavor not found!"
        echo
        echo "Please check flavor parameter with 'list' command"
        echo
        exit 1
      fi
      ;;
  esac
fi

exit 0

