#!/bin/bash

export `cat platformio.ini | grep SRC_REV | awk '{print $2}'`
DATE=`date +%Y%m%d`
OUTDIR=".pio/build"
RELDIR="releases"
BINDIR="binaries"
DEFAULT="d1mini"
INSDIR=$RELDIR/installer/canairio_installer


showHelp () {
  echo ""
  echo "***********************************************"
  echo "** Build release flavor"
  echo "***********************************************"
  echo ""
  echo "supported boards: "
  echo "d1mini, Wemos, Heltec, TTGO18650, TTGO_TQ"
  echo ""
}

updateInstallerBinaries () {
  echo ""
  echo "***********************************************"
  echo "** Update installer binaries.."
  echo "***********************************************"
  echo ""
  cp $OUTDIR/$DEFAULT/partitions.bin $INSDIR/system/
  cp ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin $INSDIR/system/
  cp ~/.platformio/packages/framework-arduinoespressif32/tools/sdk/bin/bootloader_dio_40m.bin $INSDIR/system/
  cp ~/.platformio/packages/tool-esptoolpy/esptool.py $INSDIR/
  cp ~/.platformio/packages/framework-arduinoespressif32/tools/espota.py $INSDIR/
}

updateFlavorBinaries() {
  rm $INSDIR/*.bin
  cp $RELDIR/$BINDIR/*/*${DATE}.bin $INSDIR/
}

build () {
  pio run -e $1 -t clean

  echo ""
  echo "***********************************************"
  echo "** Building $1"
  echo "***********************************************"
  echo ""

  pio run -e $1

  echo ""
  echo "***********************************************"
  echo "** Firmware $1 output:"
  echo -n "** MD5:"
  FIRMDIR=$RELDIR/$BINDIR/$1
  mkdir -p $FIRMDIR 
  cp $OUTDIR/$1/firmware.bin $FIRMDIR/canairio_${1}_rev${SRC_REV}_${DATE}.bin
  md5sum $FIRMDIR/canairio_${1}_rev${SRC_REV}_${DATE}.bin
  echo "***********************************************"
  echo ""
}

buildInstaller () {
  echo ""
  echo "***********************************************"
  echo "** Building installer"
  echo "***********************************************"
  echo ""
  mkdir -p $INSDIR
  updateInstallerBinaries
  updateFlavorBinaries
  cd $INSDIR/..
  rm -f canairio_rev${SRC_REV}_${DATE}.zip
  zip -r canairio_rev${SRC_REV}_${DATE}.zip canairio_installer
  echo ""
  du -hs canairio_rev${SRC_REV}_${DATE}.zip
  echo ""
}

printOutput () {
  FIRMDIR=$RELDIR/$BINDIR
  cd $FIRMDIR
  for flavor in *; do
    md5sum $flavor/canairio_${flavor}_rev${SRC_REV}_${DATE}.bin
  done
}


if [ "$1" = "" ]; then
  showHelp
else
  case "$1" in
    installer)
      buildInstaller
      ;;

    help)
      showHelp
      ;;

    print)
      printOutput
      ;;

    all)
      build d1mini
      build wemos
      build heltec
      build TTGO18650
      build TTGO_TQ
      echo ""
      printOutput
      echo ""
      ;;

    *)
      build $1
      ;;
  esac
fi

exit 0

