#!/bin/bash
################################################################
# CanAirIO Deploy Util
# ====================
# 
# (C) @hpsaturn 2022
#
# Original tool for deploy flavors of CanAirIO firmware.
#
# REVISIONS
# +++++++++
# 20220713 General changes for try to hava a better generic tool 
################################################################

SRC_REV=`cat platformio.ini | grep 'revision =' | awk '{print $3}'`
SRC_VER=`cat platformio.ini | grep 'version =' | awk '{print $3}'`
TARGET=`cat platformio.ini | grep 'target =' | awk '{print $3}'`
DATE=`date +%Y%m%d`
OUTDIR=".pio/build"
RELDIR="releases"
BINDIR="binaries"
MANIFEST="manifest"
NAME="canairio"
DEFAULT="TTGO_T7"
OWNER="kike-canaries"
REPO="canairio_firmware"
INSDIR=$RELDIR/installer/${NAME}_installer

flavors="TTGO_T7 WEMOSOLED HELTEC TTGO_TQ ESP32DEVKIT TTGO_TDISPLAY ESP32PICOD4 M5ATOM M5PICOD4 ESP32C3 ESP32C3OIPLUS ESP32C3LOLIN ESP32C3SEEDX ESP32S3 TTGO_T7S3 LORADEVKIT AG_OPENAIR"
#flavors="TTGO_T7 WEMOSOLED HELTEC TTGO_TQ ESP32DEVKIT TTGO_TDISPLAY ESP32PICOD4 M5STICKCPLUS M5ATOM M5PICOD4 ESP32C3 ESP32C3OIPLUS ESP32C3LOLIN ESP32C3SEEDX ESP32S3 TTGO_T7S3 LORADEVKIT AG_OPENAIR"
#flavors="TTGO_T7 WEMOSOLED ESP32DEVKIT TTGO_TDISPLAY M5STICKCPLUS M5ATOM ESP32C3 ESP32C3OIPLUS ESP32C3LOLIN ESP32C3SEEDX"
#flavors="TTGO_T7 ESP32C3 ESP32C3OIPLUS ESP32C3LOLIN ESP32C3SEEDX"

showHelp () {
  echo ""
  echo "************************************************"
  echo "** Build release flavor or installer package **"
  echo "************************************************"
  echo ""
  echo "Usage: ./build [flavor|list|all|installer|github|ota|webi|help|print|list|clean]"
  echo ""
  echo "example: ./build clean"
  echo "example: ./build all"
  echo -n "example: ./build "; echo ${flavors} | awk '{print $1}'
  echo "example: ./build installer"
  echo ""
  echo "Supported boards: "
  echo "./build list"
  echo ""
  echo "Build installer option will build a installer package for Linux"
  echo "with OTA support and USB support"
  echo ""
}

clean () {
  echo "Clean installer directory.."
  rm -rf $RELDIR/$BINDIR
  rm -rf $RELDIR/$MANIFEST
  rm -f $INSDIR/*.bin
  rm -f $INSDIR/*.py  
  for flavor in $flavors; do
    echo "Clean flavor $flavor.."
    pio run -s -e $flavor -t clean
  done
}

build () {
  echo ""
  echo "***********************************************"
  echo "** Building $1"
  echo "***********************************************"
  echo ""

  pio run -s -e $1

  echo ""
  echo "***********************************************"
  echo "** Firmware $1 output:"
  echo -n "** MD5:"
  FIRMDIR=$RELDIR/$BINDIR/$1
  mkdir -p $FIRMDIR 
  cp $OUTDIR/$1/firmware.bin $FIRMDIR/${NAME}_${1}_rev${SRC_REV}.bin
  if [ $1 == ESP32C3 ] || [ $1 == ESP32C3LOLIN ] || [ $1 == ESP32C3SEEDX ] || [ $1 == ESP32C3OIPLUS ]; then
    /usr/bin/python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool.py --chip esp32c3 merge_bin -o  $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 80m --flash_size 4MB 0x0000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
  elif [ $1 == ESP32S3 ] || [ $1 == TTGO_T7S3 ]; then
    /usr/bin/python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool.py --chip esp32s3 merge_bin -o  $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 80m --flash_size 8MB 0x0000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
  else
    esptool --chip esp32 merge_bin -o $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 40m --flash_size 4MB 0x1000 ${PIO_HOME}/packages/framework-arduinoespressif32@3.20003.220626/tools/sdk/esp32/bin/bootloader_dio_40m.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32@3.20003.220626/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
  fi
  md5sum $FIRMDIR/${NAME}_${1}_rev${SRC_REV}.bin
  md5sum $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin
  echo "***********************************************"
  echo ""
}

buildInstaller () {
  echo "***********************************************"
  echo "** Building installer with target: $TARGET"
  echo "***********************************************"
  echo ""
  echo "Update installer tool.."
  cp $PIO_HOME/packages/tool-esptoolpy@1.30300.0/esptool.py $INSDIR/
  echo "Update installer flavors.."
  rm -f $INSDIR/*.bin
  cp $RELDIR/$BINDIR/*/*${SRC_REV}_merged.bin $INSDIR/
  cp ${PIO_HOME}/packages/tool-esptoolpy/esptool.py $INSDIR/
  printOutput
  cd $INSDIR/..
  rm -f ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
  zip -r ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip ${NAME}_installer
  echo ""
  du -hs ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
  echo ""
}

publish_release () {
  cd $INSDIR/..
  # github-release upload --owner ${OWNER} --repo ${REPO} --tag "rev${SRC_REV}" --release-name "rev${SRC_REV} v${SRC_VER}" --body "${COMMIT_LOG}" ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
  echo "Publishing release: v${SRC_VER} rev${SRC_REV}" 
  echo "uploading: ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip"
  git tag -a "v${SRC_VER}" -m "release v${SRC_VER} rev${SRC_REV}"
  git push origin "v${SRC_VER}"
  git log -n 10 --pretty=format:"%h %s" | gh release create "v${SRC_VER}" -F - -t "v${SRC_VER} rev${SRC_REV}" -p ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
}

publish_release_ota () {
  scp $RELDIR/$BINDIR/*/*${SRC_REV}.bin canairio:$canairio_target/$TARGET
  scp $RELDIR/$MANIFEST/$TARGET/*.json canairio:$canairio_target/$TARGET
}

publish_release_webtools () {
  scp $INSDIR/*.bin canairio:$canairio_target/webi/$TARGET 
  scp $INSDIR/*.txt canairio:$canairio_target/webi/$TARGET 
  scp $INSDIR/*.md canairio:$canairio_target/webi/$TARGET 
  scp $RELDIR/$MANIFEST/webi/$TARGET/*.json canairio:$canairio_target/webi/$TARGET
}

printOutput () {
  echo ""
  FIRMDIR=$RELDIR/$BINDIR
  if [ ! -d "$FIRMDIR" ]; then
    echo "Please first build any flavor!"
    echo ""
    exit 1
  fi
  mkdir -p $INSDIR
  rm -f $INSDIR/md5output.txt
  touch $INSDIR/md5output.txt
  cd $FIRMDIR
  for flavor in *; do
    MD5FLAVOR=`md5sum $flavor/${NAME}_${flavor}_rev${SRC_REV}_merged.bin`
    echo $MD5FLAVOR >> ../../$INSDIR/md5output.txt
  done
  cat ../../$INSDIR/md5output.txt
  cd ../..
  echo "" 
}


if [ "$1" = "" ]; then
  showHelp
else
  case "$1" in
    clean)
      clean
      ;;

    installer)
      buildInstaller
      ;;

    help)
      showHelp
      ;;

    --help)
      showHelp
      ;;

    -help)
      showHelp
      ;;

    print)
      printOutput
      ;;

    all)
      for flavor in $flavors; do
          build $flavor
      done     
      printOutput
      ;;

    github)
      publish_release
      ;;

    ota)
      publish_release_ota
      ;;

    webi)
      publish_release_webtools
      ;;

    list)
      for flavor in $flavors; do
          echo $flavor
      done
      ;;

    *)
      if [[ $flavors == *"$1"* ]]; then
        build $1
      else
        echo ""
        echo "ERROR: Flavor not found!"
        echo ""
        echo "Please check flavor parameter with 'list' command"
        echo ""
      fi
      ;;
  esac
fi

exit 0

