#define CONFIG_KEYS_LIST            \
  X(KWIFIEN, "wifiEnable", BOOL)    \
  X(KSSID, "ssid", STRING)          \
  X(KPASS, "pass", STRING)          \
  X(KPAXENB, "paxEnable", BOOL)     \
  X(KEMOTICO, "emoEnable", BOOL)    \
  X(KI2CONLY, "i2conly", BOOL)      \
  X(KALTOFST, "altoffset", FLOAT)   \
  X(KTOFFST, "toffset", FLOAT)      \
  X(KTEMPUNT, "tunit", INT)         \
  X(KBASIC, "-----", UNKNOWN)       \
  X(KDEBUG, "debugEnable", BOOL)    \
  X(KSTYPE, "stype", INT)           \
  X(KOLEDTYPE, "oledType", INT)     \
  X(KFLIPV, "flipVEnable", BOOL)    \
  X(KHOMEAS, "homeaEnable", BOOL)   \
  X(KANAIRE, "anaireEnable", BOOL)  \
  X(KIFXENB, "ifxEnable", BOOL)     \
  X(KIFXDB, "ifxdb", STRING)        \
  X(KIFXIP, "ifxip", STRING)        \
  X(KIFXPT, "ifxpt", INT)           \
  X(KHASSIP, "hassip", STRING)      \
  X(KHASSUSR, "hassusr", STRING)    \
  X(KHASSPW, "hasspsw", STRING)     \
  X(KHASSPT, "hasspt", INT)         \
  X(KSEALVL, "sealevel", FLOAT)     \
  X(KSTIME, "stime", INT)           \
  X(KBATVMX, "battVmax", FLOAT)     \
  X(KBATVMI, "battVmin", FLOAT)     \
  X(KCHRVMX, "chrgVmin", FLOAT)     \
  X(KCHRVMI, "chrgVmax", FLOAT)     \
  X(KFAILSAFE, "fsafeEnable", BOOL) \
  X(KWKUPRST, "wkrstEnable", BOOL)  \
  X(KSOLAREN, "solarEnable", BOOL)  \
  X(KDEEPSLP, "deepSleep", INT)     \
  X(KGEIGERP, "geigerPin", INT)     \
  X(KSENHWENB, "sensorsENPin", INT)     \
  X(KFTXPWR, "forceTxPower", BOOL)  \
  X(KCOUNT, "KCOUNT", UNKNOWN)
